# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ddd9f254d99c62022fb866bb6306ef66f3d873ef7ed65f2ced50bd2b54e59e5cb470e228cb0547d60a208b18be7985061162230f824feeafd229edea720e523

test:
  secret_key_base: b8c4c1629fb1b20771790ee43e141a37377a92cf4168526ee02bfc0a12e97a270e31bf01d4e74b6695bb2c40b109050058640397d75ac2f0ee574e025bd567a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
